//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UTTT.Ejemplo.Linq.Data.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("data source=DESKTOP-ART4CME\\SQLEXPRESS;\ndatabase=Persona;\nIntegrated Security=SSP" +
            "I;\npersist security info=True;")]
        public string PersonaConnectionString {
            get {
                return ((string)(this["PersonaConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("data source=LAPTOP-DFMRNAJD;\ndatabase=Persona;\nIntegrated Security=SSPI;\n        " +
            "    \npersist security info=True;user id=sa;")]
        public string PersonaConnectionString1 {
            get {
                return ((string)(this["PersonaConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("workstation id=Ferreteria.mssql.somee.com;packet size=4096;user id=EsainF_SQLLogin_1;pwd=oobbe43dvd;data source=Ferreteria.mssql.somee.com;persist security info=False;initial catalog=Ferreteria")]
        
        //data source=.;\ndatabase=Ferreteria;\nIntegrated Security=SSPI;\n\npersist security info=True;user id=sa;"
        //"workstation id=Ferreteria.mssql.somee.com;packet size=4096;user id=EsainF_SQLLogin_1;pwd=oobbe43dvd;data source=Ferreteria.mssql.somee.com;persist security info=False;initial catalog=Ferreteria"
        public string FerreteriaConnectionString {
            get {
                return ((string)(this["FerreteriaConnectionString"]));
            }
        }
    }
}
